from typing import Tuple, Iterator, Any
import grpc
import os
import sys
# Adding protos module path if needed
script_dir = os.path.dirname(os.path.abspath(__file__))
proto_module = os.path.join(script_dir, "protos")
if proto_module not in sys.path:
    # Insert the protos modules path at the beginning of sys.path (to give it higher priority)
    sys.path.insert(0, proto_module)
from functools import partial
from sylk.commons.interceptors import sylk_client_pre_rpc, SylkSimpleAuth
import logging
from .protos.sylklabs.Todos.v1 import Todos_pb2 as Todos_v1, Todos_pb2_grpc as Todos_v1_grpc
from google.protobuf import wrappers_pb2
from google.protobuf import any_pb2
from google.protobuf import timestamp_pb2
from google.protobuf import struct_pb2
from google.protobuf import duration_pb2
from google.protobuf import field_mask_pb2
from google.protobuf import empty_pb2

# For available channel options in python visit https://github.com/grpc/grpc/blob/v1.46.x/include/grpc/impl/codegen/grpc_types.h
_CHANNEL_OPTIONS = (("grpc.keepalive_permit_without_calls", 1),
	("grpc.keepalive_time_ms", 120000),
	("grpc.keepalive_timeout_ms", 20000),
	("grpc.http2.min_time_between_pings_ms", 120000),
	("grpc.http2.max_pings_without_data", 1),)

# Global metadata
_METADATA = (('sylk-version','0.3.4'),)

# Global auth key that will be verified by sylk client
_GLOBAL_AUTH_KEY = None

# Generated thanks to [sylk.build](https://www.sylk.build)



class TaskService_v1:
	"""
	service class generated by sylk.build

	File: sylklabs.Todos.v1.TaskService
	Service: TaskService
	Version: v1
	"""

	def __init__(self,channel: grpc.ChannelCredentials = None, client_opt = {}):
		logging.root.setLevel(client_opt.get('log_level','ERROR'))
		if channel is None:
			self.channel = grpc.insecure_channel('{0}:{1}'.format(client_opt.get('host','localhost'), client_opt.get('port',44880)),_CHANNEL_OPTIONS)
			try:
				grpc.channel_ready_future(self.channel).result(timeout=client_opt.get('timeout',10))
			except grpc.FutureTimeoutError:
				logging.error('Timedout: server seems to be offline. verify your connection configs.')
				sys.exit(1)
		else:
			self.channel = channel
		self.TaskService_v1_stub = Todos_v1_grpc.TaskServiceStub(self.channel)

	def GetTask_WithCall(self, request: Todos_v1.TaskId, metadata: Tuple[Tuple[str,str]] = _METADATA) -> Tuple[Todos_v1.Task, Any]:
		"""sylk -  Returns: RPC output and a call object"""

		return self.TaskService_v1_stub.GetTask.with_call(request,metadata=metadata)

	
	def GetTask(self, request: Todos_v1.TaskId, metadata: Tuple[Tuple[str,str]] = _METADATA) -> Todos_v1.Task:
		"""sylk - """

		return self.TaskService_v1_stub.GetTask(request,metadata=metadata)