# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sylklabs.Todos.v1 import Todos_pb2 as sylklabs_dot_Todos_dot_v1_dot_Todos__pb2


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTask = channel.unary_unary(
                '/sylklabs.Todos.v1.TaskService/GetTask',
                request_serializer=sylklabs_dot_Todos_dot_v1_dot_Todos__pb2.TaskId.SerializeToString,
                response_deserializer=sylklabs_dot_Todos_dot_v1_dot_Todos__pb2.Task.FromString,
                )


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTask(self, request, context):
        """[Todos.v1.TaskService.GetTask] - 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=sylklabs_dot_Todos_dot_v1_dot_Todos__pb2.TaskId.FromString,
                    response_serializer=sylklabs_dot_Todos_dot_v1_dot_Todos__pb2.Task.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylklabs.Todos.v1.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sylklabs.Todos.v1.TaskService/GetTask',
            sylklabs_dot_Todos_dot_v1_dot_Todos__pb2.TaskId.SerializeToString,
            sylklabs_dot_Todos_dot_v1_dot_Todos__pb2.Task.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
